### PR TITLE
Extract eutr and id to use as nft

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16#-O5DbSVZ9X49k2UszGzq:-O5DbSVZ9X49k2UszGzr:b74mwdm) (no related file):*
Are you making any assumptions on uniqueness of p2p and e2e message identifiers ?

___

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16#-O5DbSVZ9X49k2UszGzq:-O5HNOyI6rmVUN7XzhVf:b-v7bs1f) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Are you making any assumptions on uniqueness of p2p and e2e message identifiers ?
</blockquote></details>

e2e ids are unique between two debtor and creditors and p2p is unique between two immediate parties. also uetr is just UUID4 so, it is universally unique

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16#-O5DbSVZ9X49k2UszGzq:-O5Hq3EF3JLGFjM_R2rB:b8kxnpi) (no related file):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

e2e ids are unique between two debtor and creditors and p2p is unique between two immediate parties. also uetr is just UUID4 so, it is universally unique
</blockquote></details>

it was decided in the call to add uniqueness check for EUTR. 

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
