### PR TITLE
WAL, batching, deduplication and tests

### PR DESCRIPTION
**Pull request by masihyeganeh**
- Add test for all pacs messages
- Refactor to add queue and message ID and small fixes
- Add batching and deduplication

This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
Give this PR a meaningful name. and make sure that it will be squashed and merged

> Reviewed 76 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3#-:-O29bZ0V1c7utBBj9Vm7:bm3aej6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3#-O29dQHe2SnQ-ZhOJGKF:-O29dQHf-lLNirkQ8Aeu:b4gvdmw) (no related file):*
give this PR a meaningful name.

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by masihyeganeh — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3#-:-O29kHgp40OWRiuZI3rg:bb6un1j)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3#-O29dQHe2SnQ-ZhOJGKF:-O29kGYu1pNkTLgXVc0x:bb6un1j) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

give this PR a meaningful name.
</blockquote></details>

Done

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
