### PR TITLE
Add the DTIF process

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

___
*[`iso20022/dtif/auxiliary_digital_token.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13#-O4Kmvy946cL6NzUfln_:-O4Kmvy946cL6NzUflna:b4yjycc) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/d0ac078c18ce166de4a2ca28d471ae3fd471e80e/iso20022/dtif/auxiliary_digital_token.go#L1)):*
> ```Go
> package dtif
> ```

I am guessing that all the files in dtif folder are auto generated from an xsd ?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`iso20022/dtif/auxiliary_digital_token.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13#-O4Kmvy946cL6NzUfln_:-O4KtjScArKfffxzyDsq:b88zoly) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/d0ac078c18ce166de4a2ca28d471ae3fd471e80e/iso20022/dtif/auxiliary_digital_token.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am guessing that all the files in dtif folder are auto generated from an xsd ?
</blockquote></details>

They are auto-generated from JSON-Schema on DTIF website, but then I did some changes

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13#-O4L7DQc-8swcXrO8aXt:-O4L7DQd3jHWjXGm-tmQ:bfjyrnt) (no related file):*
make sure to filter out the tokens that are not in coreum chain.

___

**Review by miladz68 — COMMENTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13#-O4L7DQc-8swcXrO8aXt:-O4LLX8W5GU86_dmiO3e:b-p73moh) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

make sure to filter out the tokens that are not in coreum chain.
</blockquote></details>

Just added a task for it

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
